#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/keys

# create keys
[[ ! -e /config/keys/certificate.pem ]] && \
	openssl req -x509 -nodes -days 3650 \
	-newkey rsa:2048 -keyout /config/keys/private-key.pem  -out /config/keys/certificate.pem \
	-subj "/CN=kodi"

# copy config
[[ ! -e /config/config.js ]] && \
	cp /defaults/config.js /config/config.js
[[ -f /app/kodikontrol/config.js ]] && \
	rm /app/kodikontrol/config.js
[[ ! -L /app/kodikontrol/config.js ]] && \
	ln -s /config/config.js /app/kodikontrol/config.js

cp /config/keys/*.pem /app/kodikontrol/ssl/


# permissions
chown abc:abc -R \
	/config
